version: "3"

volumes:
  pgdata:
  mongodata:

services:
  mongo:
    image: mongo:3.4.4
    ports:
      - 27017

  go-service:
    image: golang:1.9-alpine
    depends_on:
      - mongo
    command: go test -v ./..
    volumes:
      - .:/go/src/github.com/willyyang/semaphore_test
    working_dir: /go/src/github.com/willyyang/semaphore_test

