version: 2

jobs:
  install_compose:
    docker:
      - image: circleci/cci-demo-docker-primary:0.0.2
    working_directory: /go/src/github.com/circleci/cci-demo-docker
   
    steps:
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose            
            chmod +x /usr/local/bin/docker-compose

  test_1:
    machine: true
    working_directory: ~/testDir  
    steps:
      - checkout
      - run:
          name: Run test 1
          command: |
            set -x
            docker-compose run --rm go-service go test -v t_test.go

  test_2:
    machine: true
    working_directory: ~/testDir
    steps:
      - checkout
      - run:
          name: Run test 2
          command: |
            set -x
            docker-compose run --rm go-service-2 go test -v t1_test.go

  test_fail:
    machine: true
    working_directory: ~/testDir
    steps:
      - checkout
      - run:
          name: Run test 2
          command: |
            set -x
            docker-compose run --rm go-service go test -v fail_test.go
  
  after_test:
    docker:
      - image: circleci/cci-demo-docker-primary:0.0.2
    working_directory: /go/src/github.com/circleci/cci-demo-docker
   
    steps:
      - run:
          name: Check
          command: |
            set -x
            ls -al
  
workflows:
  version: 2
  run_things:
    jobs:
      - install_compose
      - test_1:
          requires:
            - install_compose
      - test_2:
          requires:
            - install_compose
      - test_fail:
          requires:
            - install_compose
      - after_test:
          requires:
            - test_1
            - test_2
            - test_fail

